[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"


[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:8080"
healthcheckPath = "/health"
healthcheckTimeout = 300

[build.env]
PYTHON_VERSION = "3.11.7"