[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.9"